-- 코드를 입력하세요
# SELECT DATE_FORMAT(O.SALES_DATE, '%Y-%m-%d') SALES_DATE,O.PRODUCT_ID,USER_ID, O.SALES_AMOUNT, F.SALES_AMOUNT
# from ONLINE_SALE O
# inner join OFFLINE_SALE F
# on O.PRODUCT_ID = F.PRODUCT_ID
# where O.SALES_DATE like '2022-03%'
# order by O.SALES_DATE, O.PRODUCT_ID, USER_ID
# ALTER TABLE OFFLINE_SALE ADD USER_ID INTEGER DEFAULT 'NULL';
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID, SALES_AMOUNT
from ONLINE_SALE where SALES_DATE like '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE,PRODUCT_ID, Null USER_ID, SALES_AMOUNT
from OFFLINE_SALE where SALES_DATE like '2022-03%'
order by SALES_DATE, PRODUCT_ID, USER_ID
