-- 코드를 입력하세요
SELECT REST_INFO.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE), 2) SCORE
from REST_INFO 
inner join REST_REVIEW 
on REST_INFO.REST_ID = REST_REVIEW.REST_ID 
group by REST_ID having ADDRESS like '서울%'
# where ADDRESS like '서울%'
order by SCORE desc, FAVORITES desc