-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID,ITEM_NAME,RARITY
from ITEM_INFO
inner join ITEM_TREE
on ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
where PARENT_ITEM_ID is not NULL 
and (SELECT RARITY from ITEM_INFO where ITEM_INFO.ITEM_ID  = PARENT_ITEM_ID) = 'RARE'
order by ITEM_ID desc